springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    path: /swagger-ui.html
#  paths-to-match:
#    - /api/v1/**
#    - /test/**

spring:
  messages:
    encoding: UTF-8
    basename: i18n/exception
  main:
    allow-bean-definition-overriding: true
